apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mellanox.com/v1alpha1","kind":"NicClusterPolicy","metadata":{"annotations":{},"name":"nic-cluster-policy"},"spec":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"node-role.kubernetes.io/worker","operator":"Exists"},{"key":"node-role.kubernetes.io/master","operator":"DoesNotExist"}]}]}},"ofedDriver":{"env":[{"name":"UNLOAD_STORAGE_MODULES","value":"true"}],"image":"doca-driver","livenessProbe":{"initialDelaySeconds":30,"periodSeconds":30},"readinessProbe":{"initialDelaySeconds":10,"periodSeconds":30},"repository":"nvcr.io/nvidia/mellanox","startupProbe":{"initialDelaySeconds":10,"periodSeconds":20},"upgradePolicy":{"autoUpgrade":true,"drain":{"deleteEmptyDir":true,"enable":true,"force":true,"timeoutSeconds":300},"maxParallelUpgrades":1},"version":"doca3.2.0-25.10-1.2.8.0-2"},"rdmaSharedDevicePlugin":{"config":"{\n  \"configList\": [\n    {\n      \"resourceName\": \"rdma_shared_device\",\n      \"rdmaHcaMax\": 1000,\n      \"selectors\": {\n        \"ifNames\": [\"ibp24s0\", \"ibp64s0\", \"ibp79s0\", \"ibp94s0\", \"ibp154s0\", \"ibp192s0\", \"ibp206s0\", \"ibp220s0\", \"ibs2f0\", \"ibs8f0\", \"ens2f1np1\", \"ens8f1np1\"]\n      }\n    }\n  ]\n}\n","image":"k8s-rdma-shared-dev-plugin","repository":"nvcr.io/nvidia/mellanox","version":"network-operator-v25.10.0"},"sriovDevicePlugin":{"config":"{\n  \"resourceList\": [\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp24s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp24s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp64s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp64s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp79s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp79s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp94s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp94s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp154s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp154s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp192s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp192s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp206s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp206s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibp220s0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibp220s0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibs2f0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibs2f0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ibs8f0\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ibs8f0#0-15\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ens2f1np1\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ens2f1np1#0-7\"],\n        \"isRdma\": true\n      }\n    },\n    {\n      \"resourcePrefix\": \"nvidia.com\",\n      \"resourceName\": \"ens8f1np1\",\n      \"selectors\": {\n        \"vendors\": [\"15b3\"],\n        \"devices\": [\"101e\"],\n        \"drivers\": [\"mlx5_core\"],\n        \"pfNames\": [\"ens8f1np1#0-7\"],\n        \"isRdma\": true\n      }\n    }\n  ]\n}\n","image":"sriov-network-device-plugin","repository":"nvcr.io/nvidia/mellanox","version":"network-operator-v25.10.0"}}}
  creationTimestamp: "2026-01-27T15:06:20Z"
  generation: 4
  name: nic-cluster-policy
  resourceVersion: "17436766"
  uid: 4c26fdaf-f281-42ab-8854-381d2f1649fb
spec:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/worker
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist
  ofedDriver:
    env:
    - name: UNLOAD_STORAGE_MODULES
      value: "true"
    forcePrecompiled: false
    image: doca-driver
    imagePullSecrets: []
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    repository: nvcr.io/nvidia/mellanox
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 20
    terminationGracePeriodSeconds: 300
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
      safeLoad: false
    version: doca3.2.0-25.10-1.2.8.0-2
  rdmaSharedDevicePlugin:
    config: |
      {
        "configList": [
          {
            "resourceName": "rdma_shared_device",
            "rdmaHcaMax": 1000,
            "selectors": {
              "ifNames": ["ibp24s0", "ibp64s0", "ibp79s0", "ibp94s0", "ibp154s0", "ibp192s0", "ibp206s0", "ibp220s0", "ibs2f0", "ibs8f0", "ens2f1np1", "ens8f1np1"]
            }
          }
        ]
      }
    image: k8s-rdma-shared-dev-plugin
    imagePullSecrets: []
    repository: nvcr.io/nvidia/mellanox
    version: network-operator-v25.10.0
  sriovDevicePlugin:
    config: |
      {
        "resourceList": [
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp24s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp24s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp64s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp64s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp79s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp79s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp94s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp94s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp154s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp154s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp192s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp192s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp206s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp206s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibp220s0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibp220s0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibs2f0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibs2f0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ibs8f0",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ibs8f0#0-15"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ens2f1np1",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ens2f1np1#0-7"],
              "isRdma": true
            }
          },
          {
            "resourcePrefix": "nvidia.com",
            "resourceName": "ens8f1np1",
            "selectors": {
              "vendors": ["15b3"],
              "devices": ["101e"],
              "drivers": ["mlx5_core"],
              "pfNames": ["ens8f1np1#0-7"],
              "isRdma": true
            }
          }
        ]
      }
    image: sriov-network-device-plugin
    imagePullSecrets: []
    repository: nvcr.io/nvidia/mellanox
    version: network-operator-v25.10.0
status:
  appliedStates:
  - name: state-multus-cni
    state: ignore
  - name: state-container-networking-plugins
    state: ignore
  - name: state-ipoib-cni
    state: ignore
  - name: state-OFED
    state: notReady
  - name: state-SRIOV-device-plugin
    state: ready
  - name: state-RDMA-device-plugin
    state: ready
  - name: state-ib-kubernetes
    state: ignore
  - name: state-nv-ipam-cni
    state: ignore
  - name: state-nic-feature-discovery
    state: ignore
  - name: state-doca-telemetry-service
    state: ignore
  - name: state-nic-configuration-operator
    state: ignore
  - name: state-spectrum-x-operator
    state: ignore
  state: notReady
