apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gaie-aggregated-manifests-configmap.yaml
  - install-gaie-aggregated-job.yaml
  - envoyfilter.yaml

commonLabels:
  component: inferencepool-controller-aggregated
