apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: openshift-gitops
data:
  resource.exclusions: |
    - apiGroups:
      - ""
      - discovery.k8s.io
      clusters:
      - '*'
      kinds:
      - Endpoints
      - EndpointSlice
    - apiGroups:
      - apiregistration.k8s.io
      clusters:
      - '*'
      kinds:
      - APIService
    - apiGroups:
      - coordination.k8s.io
      clusters:
      - '*'
      kinds:
      - Lease
    - apiGroups:
      - authentication.k8s.io
      - authorization.k8s.io
      clusters:
      - '*'
      kinds:
      - SelfSubjectReview
      - TokenReview
      - LocalSubjectAccessReview
      - SelfSubjectAccessReview
      - SelfSubjectRulesReview
      - SubjectAccessReview
    - apiGroups:
      - visibility.kueue.x-k8s.io
      kinds:
      - "*"
      clusters:
      - "*"
