#!/bin/bash
# Shared GPU and RDMA resource discovery script
# Used by all llm-d overlays to dynamically discover:
# - GPU count per node
# - Available RDMA resources (NVIDIA shared, SR-IOV, rdma/)
# - Generate Helm values with proper resource requests

set -e

# Output file for discovered resources
OUTPUT_FILE="${OUTPUT_FILE:-/tmp/discovered-resources.yaml}"
NODE_SELECTOR="${NODE_SELECTOR:-}"  # Optional: specific node to query
NAMESPACE="${NAMESPACE:-llm-d}"

echo "🔍 Discovering GPU and RDMA resources..."

# Get nodes with GPUs
if [ -n "$NODE_SELECTOR" ]; then
  NODES=$(kubectl get nodes -l "$NODE_SELECTOR" -o json)
else
  NODES=$(kubectl get nodes -o json)
fi

# Find nodes with GPUs
GPU_NODES=$(echo "$NODES" | jq -r '.items[] | select(.status.allocatable["nvidia.com/gpu"]? != null and (.status.allocatable["nvidia.com/gpu"] | tonumber) > 0) | .metadata.name')

if [ -z "$GPU_NODES" ]; then
  echo "❌ No GPU nodes found!"
  exit 1
fi

GPU_NODE_COUNT=$(echo "$GPU_NODES" | wc -l | tr -d ' ')
echo "📊 Found $GPU_NODE_COUNT GPU node(s)"

# Pick first GPU node to analyze resources
SAMPLE_NODE=$(echo "$GPU_NODES" | head -1)
echo "📝 Analyzing resources on node: $SAMPLE_NODE"

# Get allocatable resources for the sample node
ALLOCATABLE=$(kubectl get node "$SAMPLE_NODE" -o json | jq '.status.allocatable')

# Discover GPU count
GPU_COUNT=$(echo "$ALLOCATABLE" | jq -r '."nvidia.com/gpu" // "0"' | sed 's/[^0-9]//g')
echo "   🎮 GPUs per node: $GPU_COUNT"

# Discover RDMA resources (all types with non-zero allocatable)
# Include: rdma/*, openshift.io/*rdma, openshift.io/*ib, nvidia.com/*rdma, nvidia.com/*ib
RDMA_RESOURCES=$(echo "$ALLOCATABLE" | jq -r '
  to_entries |
  map(select(
    (.key | startswith("rdma/")) or
    (.key | startswith("openshift.io/") and (.key | contains("rdma") or contains("ib") or contains("roce"))) or
    (.key | startswith("nvidia.com/") and (.key | contains("rdma") or contains("ib") or contains("roce")))
  )) |
  map(select(
    (.value | tostring | test("^[0-9]+$")) and
    (.value | tonumber) > 0
  )) |
  map("\(.key):\(.value)") |
  .[]
')

if [ -z "$RDMA_RESOURCES" ]; then
  echo "   ⚠️  No RDMA resources found"
  RDMA_COUNT=0
else
  RDMA_COUNT=$(echo "$RDMA_RESOURCES" | wc -l | tr -d ' ')
  echo "   🌐 RDMA/IB resources found: $RDMA_COUNT"
  echo "$RDMA_RESOURCES" | while IFS=: read -r resource count; do
    echo "      - $resource: $count"
  done
fi

# Generate resource limits/requests YAML fragment
echo ""
echo "📦 Generating resource configuration..."

cat > "$OUTPUT_FILE" << EOF
# Auto-generated by discover-gpu-rdma.sh
# Node: $SAMPLE_NODE
# Discovery time: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

discovered:
  gpuCount: $GPU_COUNT
  rdmaCount: $RDMA_COUNT
  tensorParallelSize: $GPU_COUNT
  nodeCount: $GPU_NODE_COUNT

# Resource limits and requests for Kubernetes pods
resources:
  limits:
    cpu: "32"
    memory: "256Gi"
    nvidia.com/gpu: "$GPU_COUNT"
EOF

# Add RDMA resources to limits
if [ -n "$RDMA_RESOURCES" ]; then
  echo "$RDMA_RESOURCES" | while IFS=: read -r resource count; do
    echo "    $resource: \"1\"" >> "$OUTPUT_FILE"
  done
fi

cat >> "$OUTPUT_FILE" << EOF
  requests:
    cpu: "32"
    memory: "256Gi"
    nvidia.com/gpu: "$GPU_COUNT"
EOF

# Add RDMA resources to requests
if [ -n "$RDMA_RESOURCES" ]; then
  echo "$RDMA_RESOURCES" | while IFS=: read -r resource count; do
    echo "    $resource: \"1\"" >> "$OUTPUT_FILE"
  done
fi

# Generate vLLM environment and command arguments
cat >> "$OUTPUT_FILE" << EOF

# vLLM configuration
vllm:
  tensorParallelSize: $GPU_COUNT
  # Recommended: Set to match GPU count for tensor parallelism
  # Adjust based on your model size and deployment pattern

# RDMA device list (for NCCL_IB_HCA)
rdmaDevices:
EOF

if [ -n "$RDMA_RESOURCES" ]; then
  # Extract device names for NCCL configuration
  # For rdma/rdma_shared_nicX, extract the NIC name
  echo "$RDMA_RESOURCES" | grep "^rdma/" | while IFS=: read -r resource count; do
    DEVICE_NAME=$(echo "$resource" | sed 's|^rdma/rdma_shared_||')
    echo "  - $DEVICE_NAME" >> "$OUTPUT_FILE"
  done
fi

echo ""
echo "✅ Discovery complete!"
echo "   Output: $OUTPUT_FILE"
echo ""
echo "Summary:"
echo "  - GPUs: $GPU_COUNT per node"
echo "  - RDMA resources: $RDMA_COUNT"
echo "  - Tensor parallel size: $GPU_COUNT"
echo "  - GPU nodes: $GPU_NODE_COUNT"
