apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: infra-aggregated-gateway
  namespace: llm-d
  labels:
    app: llm-d
    component: multinode-aggregated
  annotations:
    argocd.argoproj.io/sync-wave: "35"
    description: "External route for inference gateway"
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: infra-aggregated-gateway-istio
    weight: 100
  wildcardPolicy: None
