apiVersion: v1
kind: Service
metadata:
  name: pd-prefill
  namespace: llm-d
  labels:
    app: llm-d
    component: pd-disaggregation-multinode
    llm-d.ai/inference-serving: "true"
    llm-d.ai/role: prefill
  annotations:
    argocd.argoproj.io/sync-wave: "24"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: metrics
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/role: prefill
